### ISSUE TITLE
security concerns with timing attack in bn.js use

### ISSUE THREAD

**Issue by pravi** [crypto-browserify/browserify-rsa#11]
I think https://github.com/crypto-browserify/diffie-hellman/issues/22 is also applicable here.

**Comment by calvinmetcalf** [comment]
We use a blind in our calculations just like how libressl does, if you had
read through the DiffieHellman issue you would have noted that the issue
there is a different type of constant time thing they use in libressl that
I'm not sure how to replicate in JavaScript, any ideas there would be
helpful.

If I'm misreading your comment you think there is a flaw in how we are
doing the blinding in this library or there is an additional safeguard we
can use I'm all ears.

That being said this is a port of the nodejs api which is frustratingly
synchronous so we are unable to take advantage native crypto abilities in
the browser so I'd honestly be very hesitant to recommend this for anything
other then verification

**Comment by pravi** [comment]
I was just confirming since this library also uses bn.js. Thanks for your comment.
